default: &default
  adapter: postgresql
  encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
  pool: <%= ENV.fetch('RAILS_MAX_POOLS', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: fantasea_development

development:
  <<: *default

test:
  <<: *default
  database: fantasea_test

production:
  <<: *default
  database: fantaprod
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
