default: &default
  adapter: postgresql
  encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
  # port: <%= ENV.fetch('DB_PORT', '5432') %>
  pool: <%= ENV.fetch('RAILS_MAX_POOLS', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: 'fantasea_development'

test:
  <<: *default
  database: 'fantasea_test'

development:
  <<: *default

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>_production
