default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fanta_development

test:
  <<: *default
  database: fanta_test

production:
  <<: *default
  database: fantaprod
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)


# default: &default
#   adapter: postgresql
#   encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
#   port: 5432
#   pool:  5
#   host:  localhost
#   database: fanta
#   username: mono
#   password: qweasd123
#   timeout: 5000

# test:
#   <<: *default

# development:
#   <<: *default


# staging:
#   <<: *default

# production:
#   <<: *default
