default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_POOLS', 5) %>

development:
  <<: *default
  timeout: 5000
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>_test

staging:
  <<: *default

production:
  <<: *default
  database: fanta_prod
  username: <%= Rails.application.credentials.produser[:user]  %>
  password: <%= Rails.application.credentials.prodpass[:pass]  %>
