default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fanta_development

test:
  <<: *default
  database: fanta_test

production:
  <<: *default
  database: fanta_prod
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
